version: '3.8'

services:
  servicio2:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - POSTGRES_DB=MovieNest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=camila123
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5433
    depends_on:
      - postgres
    networks:
      - g2net


networks:
  g2net:
    driver: bridge