version: '3.8'

services:
  servicio2:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - POSTGRES_DB=MovieNest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=camila123
      - POSTGRES_HOST=postgres     # Nombre del servicio de la base de datos
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
    networks:
      - g2net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: MovieNest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: camila123
    ports:
      - "5433:5432"
    networks:
      - g2net

networks:
  g2net:
    driver: bridge
